SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE organizations (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at DOUBLE NOT NULL,
  updated_at DOUBLE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE workspaces (
  id VARCHAR(64) PRIMARY KEY,
  organization_id VARCHAR(64),
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255),
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at DOUBLE NOT NULL,
  updated_at DOUBLE NOT NULL,
  INDEX ix_workspaces_organization_id (organization_id),
  CONSTRAINT fk_workspaces_organization
    FOREIGN KEY (organization_id) REFERENCES organizations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE users (
  id VARCHAR(64) PRIMARY KEY,
  email VARCHAR(255) UNIQUE,
  display_name VARCHAR(255),
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at DOUBLE NOT NULL,
  updated_at DOUBLE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE roles (
  id VARCHAR(64) PRIMARY KEY,
  code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  is_system TINYINT(1) NOT NULL DEFAULT 0,
  created_at DOUBLE NOT NULL,
  updated_at DOUBLE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE memberships (
  id VARCHAR(64) PRIMARY KEY,
  organization_id VARCHAR(64),
  workspace_id VARCHAR(64),
  user_id VARCHAR(64) NOT NULL,
  role_id VARCHAR(64),
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at DOUBLE NOT NULL,
  updated_at DOUBLE NOT NULL,
  INDEX ix_memberships_organization_id (organization_id),
  INDEX ix_memberships_workspace_id (workspace_id),
  INDEX ix_memberships_user_id (user_id),
  INDEX ix_memberships_role_id (role_id),
  CONSTRAINT fk_memberships_organization FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_memberships_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id),
  CONSTRAINT fk_memberships_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_memberships_role FOREIGN KEY (role_id) REFERENCES roles(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE billing_accounts (
  id VARCHAR(64) PRIMARY KEY,
  organization_id VARCHAR(64),
  workspace_id VARCHAR(64),
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  billing_email VARCHAR(255),
  metadata JSON NOT NULL,
  created_at DOUBLE NOT NULL,
  updated_at DOUBLE NOT NULL,
  INDEX ix_billing_accounts_organization_id (organization_id),
  INDEX ix_billing_accounts_workspace_id (workspace_id),
  CONSTRAINT fk_billing_accounts_organization FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_billing_accounts_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE series (
  id VARCHAR(64) PRIMARY KEY,
  organization_id VARCHAR(64),
  workspace_id VARCHAR(64),
  created_by VARCHAR(64),
  updated_by VARCHAR(64),
  created_at DOUBLE NOT NULL,
  updated_at DOUBLE NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  art_direction JSON,
  model_settings JSON NOT NULL,
  prompt_config JSON NOT NULL,
  INDEX ix_series_organization_id (organization_id),
  INDEX ix_series_workspace_id (workspace_id),
  INDEX ix_series_org_workspace_updated (organization_id, workspace_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE projects (
  id VARCHAR(64) PRIMARY KEY,
  organization_id VARCHAR(64),
  workspace_id VARCHAR(64),
  created_by VARCHAR(64),
  updated_by VARCHAR(64),
  created_at DOUBLE NOT NULL,
  updated_at DOUBLE NOT NULL,
  title VARCHAR(255) NOT NULL,
  original_text TEXT NOT NULL,
  style_preset VARCHAR(128) NOT NULL DEFAULT 'realistic',
  style_prompt TEXT,
  merged_video_url TEXT,
  series_id VARCHAR(64),
  episode_number INT,
  art_direction JSON,
  model_settings JSON NOT NULL,
  prompt_config JSON NOT NULL,
  INDEX ix_projects_organization_id (organization_id),
  INDEX ix_projects_workspace_id (workspace_id),
  INDEX ix_projects_series_id (series_id),
  INDEX ix_projects_org_workspace_updated (organization_id, workspace_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE characters (
  id VARCHAR(64) PRIMARY KEY,
  organization_id VARCHAR(64),
  workspace_id VARCHAR(64),
  created_by VARCHAR(64),
  updated_by VARCHAR(64),
  created_at DOUBLE NOT NULL,
  updated_at DOUBLE NOT NULL,
  owner_type VARCHAR(32) NOT NULL,
  owner_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  age VARCHAR(128),
  gender VARCHAR(64),
  clothing TEXT,
  visual_weight INT NOT NULL DEFAULT 3,
  full_body_image_url TEXT,
  full_body_prompt TEXT,
  full_body_asset_selected_id VARCHAR(64),
  three_view_image_url TEXT,
  three_view_prompt TEXT,
  three_view_asset_selected_id VARCHAR(64),
  headshot_image_url TEXT,
  headshot_prompt TEXT,
  headshot_asset_selected_id VARCHAR(64),
  video_prompt TEXT,
  image_url TEXT,
  avatar_url TEXT,
  is_consistent TINYINT(1) NOT NULL DEFAULT 1,
  full_body_updated_at DOUBLE NOT NULL,
  three_view_updated_at DOUBLE NOT NULL DEFAULT 0,
  headshot_updated_at DOUBLE NOT NULL DEFAULT 0,
  base_character_id VARCHAR(64),
  voice_id VARCHAR(128),
  voice_name VARCHAR(255),
  voice_speed DOUBLE NOT NULL DEFAULT 1.0,
  voice_pitch DOUBLE NOT NULL DEFAULT 1.0,
  voice_volume INT NOT NULL DEFAULT 50,
  locked TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  INDEX ix_characters_organization_id (organization_id),
  INDEX ix_characters_workspace_id (workspace_id),
  INDEX ix_characters_owner (owner_type, owner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE scenes (
  id VARCHAR(64) PRIMARY KEY,
  organization_id VARCHAR(64),
  workspace_id VARCHAR(64),
  created_by VARCHAR(64),
  updated_by VARCHAR(64),
  created_at DOUBLE NOT NULL,
  updated_at DOUBLE NOT NULL,
  owner_type VARCHAR(32) NOT NULL,
  owner_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  visual_weight INT NOT NULL DEFAULT 3,
  time_of_day VARCHAR(128),
  lighting_mood TEXT,
  image_url TEXT,
  image_selected_id VARCHAR(64),
  video_prompt TEXT,
  locked TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  INDEX ix_scenes_organization_id (organization_id),
  INDEX ix_scenes_workspace_id (workspace_id),
  INDEX ix_scenes_owner (owner_type, owner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE props (
  id VARCHAR(64) PRIMARY KEY,
  organization_id VARCHAR(64),
  workspace_id VARCHAR(64),
  created_by VARCHAR(64),
  updated_by VARCHAR(64),
  created_at DOUBLE NOT NULL,
  updated_at DOUBLE NOT NULL,
  owner_type VARCHAR(32) NOT NULL,
  owner_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  video_url TEXT,
  audio_url TEXT,
  sfx_url TEXT,
  bgm_url TEXT,
  image_url TEXT,
  image_selected_id VARCHAR(64),
  video_prompt TEXT,
  locked TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  INDEX ix_props_organization_id (organization_id),
  INDEX ix_props_workspace_id (workspace_id),
  INDEX ix_props_owner (owner_type, owner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE character_asset_units (
  id VARCHAR(64) PRIMARY KEY,
  organization_id VARCHAR(64),
  workspace_id VARCHAR(64),
  created_by VARCHAR(64),
  updated_by VARCHAR(64),
  created_at DOUBLE NOT NULL,
  updated_at DOUBLE NOT NULL,
  character_id VARCHAR(64) NOT NULL,
  unit_type VARCHAR(32) NOT NULL,
  selected_image_id VARCHAR(64),
  selected_video_id VARCHAR(64),
  image_prompt TEXT,
  video_prompt TEXT,
  image_updated_at DOUBLE NOT NULL,
  video_updated_at DOUBLE NOT NULL DEFAULT 0,
  INDEX ix_character_asset_units_organization_id (organization_id),
  INDEX ix_character_asset_units_workspace_id (workspace_id),
  UNIQUE KEY ix_character_asset_units_character (character_id, unit_type),
  CONSTRAINT fk_character_asset_units_character FOREIGN KEY (character_id) REFERENCES characters(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE image_variants (
  id VARCHAR(64) PRIMARY KEY,
  organization_id VARCHAR(64),
  workspace_id VARCHAR(64),
  created_by VARCHAR(64),
  updated_by VARCHAR(64),
  created_at DOUBLE NOT NULL,
  updated_at DOUBLE NOT NULL,
  owner_type VARCHAR(32) NOT NULL,
  owner_id VARCHAR(64) NOT NULL,
  variant_group VARCHAR(64) NOT NULL,
  url TEXT NOT NULL,
  prompt_used TEXT,
  is_favorited TINYINT(1) NOT NULL DEFAULT 0,
  is_uploaded_source TINYINT(1) NOT NULL DEFAULT 0,
  upload_type VARCHAR(64),
  INDEX ix_image_variants_organization_id (organization_id),
  INDEX ix_image_variants_workspace_id (workspace_id),
  INDEX ix_image_variants_owner (owner_type, owner_id, variant_group)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE video_variants (
  id VARCHAR(64) PRIMARY KEY,
  organization_id VARCHAR(64),
  workspace_id VARCHAR(64),
  created_by VARCHAR(64),
  updated_by VARCHAR(64),
  created_at DOUBLE NOT NULL,
  updated_at DOUBLE NOT NULL,
  owner_type VARCHAR(32) NOT NULL,
  owner_id VARCHAR(64) NOT NULL,
  variant_group VARCHAR(64) NOT NULL,
  url TEXT NOT NULL,
  prompt_used TEXT,
  audio_url TEXT,
  source_image_id VARCHAR(64),
  is_favorited TINYINT(1) NOT NULL DEFAULT 0,
  INDEX ix_video_variants_organization_id (organization_id),
  INDEX ix_video_variants_workspace_id (workspace_id),
  INDEX ix_video_variants_owner (owner_type, owner_id, variant_group)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE storyboard_frames (
  id VARCHAR(64) PRIMARY KEY,
  organization_id VARCHAR(64),
  workspace_id VARCHAR(64),
  created_by VARCHAR(64),
  updated_by VARCHAR(64),
  created_at DOUBLE NOT NULL,
  updated_at DOUBLE NOT NULL,
  project_id VARCHAR(64) NOT NULL,
  frame_order INT NOT NULL,
  scene_id VARCHAR(64) NOT NULL,
  character_ids JSON NOT NULL,
  prop_ids JSON NOT NULL,
  action_description TEXT NOT NULL,
  facial_expression TEXT,
  dialogue TEXT,
  speaker VARCHAR(255),
  visual_atmosphere TEXT,
  character_acting TEXT,
  key_action_physics TEXT,
  shot_size VARCHAR(128),
  camera_angle VARCHAR(128) NOT NULL DEFAULT 'Medium Shot',
  camera_movement VARCHAR(128),
  composition TEXT,
  atmosphere TEXT,
  composition_data JSON,
  image_prompt TEXT,
  image_prompt_cn TEXT,
  image_prompt_en TEXT,
  image_url TEXT,
  image_selected_id VARCHAR(64),
  rendered_image_url TEXT,
  rendered_image_selected_id VARCHAR(64),
  video_prompt TEXT,
  video_url TEXT,
  audio_url TEXT,
  audio_error TEXT,
  sfx_url TEXT,
  selected_video_id VARCHAR(64),
  locked TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  INDEX ix_storyboard_frames_organization_id (organization_id),
  INDEX ix_storyboard_frames_workspace_id (workspace_id),
  INDEX ix_storyboard_frames_project_id (project_id),
  INDEX ix_storyboard_frames_project (project_id, frame_order),
  CONSTRAINT fk_storyboard_frames_project FOREIGN KEY (project_id) REFERENCES projects(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE video_tasks (
  id VARCHAR(64) PRIMARY KEY,
  organization_id VARCHAR(64),
  workspace_id VARCHAR(64),
  created_by VARCHAR(64),
  updated_by VARCHAR(64),
  created_at DOUBLE NOT NULL,
  updated_at DOUBLE NOT NULL,
  project_id VARCHAR(64) NOT NULL,
  frame_id VARCHAR(64),
  asset_id VARCHAR(64),
  image_url TEXT NOT NULL,
  prompt TEXT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  video_url TEXT,
  duration INT NOT NULL DEFAULT 5,
  seed INT,
  resolution VARCHAR(64) NOT NULL DEFAULT '720p',
  generate_audio TINYINT(1) NOT NULL DEFAULT 0,
  audio_url TEXT,
  prompt_extend TINYINT(1) NOT NULL DEFAULT 1,
  negative_prompt TEXT,
  model VARCHAR(128) NOT NULL DEFAULT 'wan2.6-i2v',
  shot_type VARCHAR(64) NOT NULL DEFAULT 'single',
  generation_mode VARCHAR(64) NOT NULL DEFAULT 'i2v',
  reference_video_urls JSON NOT NULL,
  mode VARCHAR(64),
  sound VARCHAR(16),
  cfg_scale DOUBLE,
  vidu_audio TINYINT(1),
  movement_amplitude VARCHAR(64),
  INDEX ix_video_tasks_organization_id (organization_id),
  INDEX ix_video_tasks_workspace_id (workspace_id),
  INDEX ix_video_tasks_project_id (project_id),
  INDEX ix_video_tasks_project (project_id, created_at),
  INDEX ix_video_tasks_owner_asset (asset_id, frame_id),
  CONSTRAINT fk_video_tasks_project FOREIGN KEY (project_id) REFERENCES projects(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;
